version: 2.0

jobs:
    build:
        working_directory: ~/pi-image
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run: ./install-dependencies.sh
            - restore_cache:
                key: baseimage-{{ .Branch }}-{{ checksum "download-image.sh" }}
            - run: ./download-image.sh
            - save_cache:
                key: baseimage-{{ .Branch }}-{{ checksum "download-image.sh" }}
            - run: ./build-image.sh
