version: 2.0

jobs:
    build:
        machine: true
        working_directory: ~/pi-image
        steps:
            - checkout
            - run: sudo ./install-dependencies.sh
            - restore_cache:
                key: baseimage-{{ .Branch }}-{{ checksum "download-image.sh" }}
            - run: ./download-image.sh /tmp/raspbian.zip
            - save_cache:
                key: baseimage-{{ .Branch }}-{{ checksum "download-image.sh" }}
                paths:
                  - /tmp/raspbian.zip
            - run: cp /tmp/raspbian.zip ./
            - run: sudo ./build-image.sh
