version: 2.0

jobs:
    build:
        working_directory: ~/pi-image
        docker:
            - image: debian:stretch
        steps:
            - checkout
            - run: ./install-dependencies.sh
            - run: ./build-image.sh
