version: 2.0

jobs:
    build:
        docker:
          - image: "ubuntu:latest"
        working_directory: ~/pi-image
        steps:
            - checkout
            - run: ./install-dependencies.sh
            - run: git submodule update --init
            - restore_cache:
                key: baseimage-{{ .Branch }}-{{ checksum "download-image.sh" }}
            - run: ./download-image.sh /tmp/raspbian.zip
            - save_cache:
                key: baseimage-{{ .Branch }}-{{ checksum "download-image.sh" }}
                paths:
                  - /tmp/raspbian.zip
            - run: cp /tmp/raspbian.zip ./
            - restore_cache:
                key: prebuilt-{{ .Branch }}-{{ checksum "download-image.sh" }}-{{ checksum "prebuild-image.sh" }}-{{ checksum "pi-prebuild.sh" }}
            - run: sudo ./prebuild-image.sh
            - save_cache:
                key: prebuilt-{{ .Branch }}-{{ checksum "download-image.sh" }}-{{ checksum "prebuild-image.sh" }}-{{ checksum "pi-prebuild.sh" }}
                paths:
                  - /tmp/raspbian-base.img
            - run: sudo ./build-image.sh
            - run: sudo ./edit-boot.sh
            - run: sudo xz --verbose -3 pi-image.img
            - store_artifacts:
                path: pi-image.img.xz
                destination: pi-image.img.xz
